# Artificial Neural Network

## Installing Theano

In [1]:
#!pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
# Theano is an open source numeric computation library, very efficient and based on numpy syntax.  Theano can not only run on 
# your CPU (Central Processing Unit) but also on your GPU (Graphical Processing Unit)
!pip install theano

## Installing Tensorflow and Keras

In [2]:
# Installing Tensorflow
# Install Tensorflow from the website: https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html
# Tensorflow is another open source numeric computation library, runs very fast computation and can run either on your CPU or GPU
# If you are using Theano and Tensorflow together it means that you are building a deep neural network FROM SCRATCH
#!pip install tensorflow
# However if you want to wrap Theano and Tensorflow together then you can directly use Keras.  This library allows us to build a
# deep neural network using a few lines of code.  Keras is extremely powerful and runs on Theano and Tensorflow libraries. 
# Installing Keras
!pip install --upgrade keras

Requirement already up-to-date: keras in c:\programdata\anaconda3\lib\site-packages (2.2.4)


# Part 1 - Data Preprocessing

In [3]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
#Since the first column is considered column "0" and we need columns from 3 to 12 - we put 3:13 (the upper bound 13 is excluded)
X = dataset.iloc[:, 3:13].values
#The label or dependent variable is the 13th variable that is considered
y = dataset.iloc[:, 13].values

In [5]:
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#Here we are encoding the country and gender features below
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
#The country variable is again changed from label encoding to one hot encoding thereby introducing dummy variables
#In the next line the [1] refers to the country variable which is the second from left.  First one being 0 and second one is 1
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
#The next line eliminates THE DUMMY VARIABLE TRAP by reducing one column.  Here whenever two columns have 0 it assumes it is the
#third country
X = X[:, 1:]

In [8]:
#We will take the first row where there is a credit score of 619.  As we can see from the result below - France corresponds to 
#zeroes in the first two columns, female is 0, if he has card then it is 1 else 0, is active member is 1 else 0.  
#These are some transformations we will make a note of for now
X[0]

array([0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [9]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
# Feature Scaling
#Feature scaling is very essential in deep learning.  It eliminates the value of one independent variable dominating the others
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

# Part 2 - Now let's make the ANN!

In [13]:
# Importing the Keras libraries and packages
import keras
#The sequential library is used to initialize our neural network
from keras.models import Sequential
#The dense library is used to build the layers of our ANN
from keras.layers import Dense

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Using TensorFlow backend.


In [14]:
# Initialising the ANN
classifier = Sequential()

In [15]:
# Adding the input layer and the first hidden layer.  Here the rectifier activation function is used for the hidden layer. 
# input_dim refers to the number of features that feed as input. This is only mentioned for the first hidden layer
# output_dim refers to the number of nodes of the first hidden layer.  Normally the number of nodes is decided as the average of
# the number of points in the input layer (number of features) and the number of points in the output layer. (i+o)/2.  Here it
# is 11+1=12/2=6
# init refers to randomly initializing the weights in the first run of forward propogation in the stochastic gradient descent. 
# You do this initialization uniformly.  Two options are glorot_uniform and uniform. 
# The activation function relu refers to the rectifier activation function
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

Instructions for updating:
Colocations handled automatically by placer.


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  if __name__ == '__main__':


In [16]:
# Adding the second hiddeclassifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))n layer.  Again the rectifier activation function is used for the hidden layer
# As you notice the input_dim is missing as we are trying to create a second hidden layer - for which input layer is not required
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [17]:
# Adding the output layer.  Here the sigmoid activation function is used for the output layer as we are looking for probabilities
# in this case the output_dim has a value of 1 as it refers to the predicted label field. 
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [18]:
# Compiling the ANN
# Optimizer is the algorithm you would use to find the optimal set of weights.  There are different types of stochastic gradient
# descent algorithms.  One of the most efficient one is the adam algorithm
# Loss refers to the loss function within the stochastic gradient descent adam algorithm. If the predicted label has two outcomes
# then the loss function used is binary_crossentropy.  If there are more than two then it is categorical_crossentropy.
# For metrics here we are going to use accuracy as a measurement to see how well the algorithm is performing
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [19]:
# Fitting the ANN to the Training set
# batch_size refers to the number of rows/observations that you want to consider for each run when calibrating the weights
# nb_epoch refers to the number of times the ann would be iterated
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

Instructions for updating:
Use tf.cast instead.


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  after removing the cwd from sys.path.


Epoch 1/100
8000/8000 [==============================] - 7s 910us/step - loss: 0.4968 - acc: 0.7952
Epoch 2/100
8000/8000 [==============================] - 3s 398us/step - loss: 0.4284 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 404us/step - loss: 0.4202 - acc: 0.8097
Epoch 4/100
8000/8000 [==============================] - 3s 336us/step - loss: 0.4137 - acc: 0.8296
Epoch 5/100
8000/8000 [==============================] - 2s 248us/step - loss: 0.4089 - acc: 0.8337
Epoch 6/100
8000/8000 [==============================] - 2s 257us/step - loss: 0.4056 - acc: 0.8335
Epoch 7/100
8000/8000 [==============================] - 2s 286us/step - loss: 0.4031 - acc: 0.8345
Epoch 8/100
8000/8000 [==============================] - 3s 341us/step - loss: 0.4008 - acc: 0.8352 0s - loss: 0.4072 - acc
Epoch 9/100
8000/8000 [==============================] - 2s 294us/step - loss: 0.4003 - acc: 0.8335
Epoch 10/100
8000/8000 [==============================] - 3s 314us/step - lo

8000/8000 [==============================] - 1s 141us/step - loss: 0.3377 - acc: 0.8611
Epoch 80/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3372 - acc: 0.8615
Epoch 81/100
8000/8000 [==============================] - 2s 223us/step - loss: 0.3362 - acc: 0.8606 0s - loss: 0.327
Epoch 82/100
8000/8000 [==============================] - 2s 232us/step - loss: 0.3373 - acc: 0.8609
Epoch 83/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.3379 - acc: 0.8577
Epoch 84/100
8000/8000 [==============================] - 2s 245us/step - loss: 0.3385 - acc: 0.8592
Epoch 85/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.3368 - acc: 0.8611 0s - loss: 0.3382 - acc: 0.8
Epoch 86/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3376 - acc: 0.8597
Epoch 87/100
8000/8000 [==============================] - 2s 217us/step - loss: 0.3357 - acc: 0.8620
Epoch 88/100
8000/8000 [==============================] - 

# Part 3 - Making the predictions and evaluating the model

In [20]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [33]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [34]:
cm

array([[1501,   94],
       [ 190,  215]], dtype=int64)

# Testing the model on a single customer to predict for churn

In [ ]:
"""Now let us make a prediction for a single row wether a customer will churn for the following values:
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $60000
Number of Products: 2
Does this customer have a credit card ? Yes
Is this customer an Active Member: Yes
Estimated Salary: $50000
So should we say goodbye to that customer ?"""

In [ ]:
"""Now we have to see how the encodings and transformations have happened while we apply the above values.  For this let us compare
the original dataset with the tranformed array of X"""
#As we saw earlier - France corresponds to zeroes in the first two columns, male is 1, He has a credit card which gives a value
#of 1, is an active member - which again takes a value of 1.  So the above data should be like this:
# 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000

In [65]:
#It is important that we pass this data as a numpy array and it is VERY IMPORTANT TO PUT IT INTO TWO SQUARE BRACKETS.  If you
#put one set of square brackets - it will consider it as column headers.  If you put two square brackets - it will take it as
#a 2 dimensional array.  
#Also since we have done scaling - we use the same sc method to transform the array - before passing it into prediction
new_prediction = classifier.predict(sc.transform(np.array([[0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
#The below code will change the prediction into True or False
new_prediction = (new_prediction > 0.5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [66]:
new_prediction

array([[False]])

# Implement K-fold cross validation to fine tune model accuracy

In [10]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
#The sequential library is used to initialize our neural network
from keras.models import Sequential
#The dense library is used to build the layers of our ANN
from keras.layers import Dense

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Using TensorFlow backend.


In [ ]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
    classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)
#In the next line we are doing the cross validation.  Here cv = 10 means that we are doing for 10 folds & n_jobs = -1 means that
#we are using all the CPU capacity to get this job done.  This will take a long time to execute.
#accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 2, n_jobs = -1)

In [ ]:
mean = accuracies.mean()
variance = accuracies.std()

# Improving the ANN performance
## Dropout Regularization to reduce overfitting

In [14]:
#Dropout Regularization to improve overfitting if needed
#This technique works this way : at each iteration of your artificial neural network - some neurons are randomly disabled to
#prevent them from being too dependent on each other(when they learn the correlations).  This way the neurons learn several
#independant correlations in the data because each time there is not the same configuration of the neurons.  The fact that we get
#these independant correlations of the data because now the neurons are working more independently : prevents the neurons from
#learning too much and therefore prevents overfitting
from keras.layers import Dropout
#You should apply dropout to all the layers. Adding dropout to first layers in next two steps
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dropout(p = 0.1))
#Adding droput to second layer in next two steps
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dropout(p = 0.1))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  # Remove the CWD from sys.path while we load stuff.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  if sys.path[0] == '':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  del sys.path[0]


In [15]:
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until


Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 2s 275us/step - loss: 0.4872 - acc: 0.7959 0s - loss: 0.5114 - acc: 
Epoch 2/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4358 - acc: 0.7960 0s - loss: 0.4409 - 
Epoch 3/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4312 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.4278 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4250 - acc: 0.8112
Epoch 6/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.4254 - acc: 0.8234
Epoch 7/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.4252 - acc: 0.8260 0s - loss: 0.4243 - acc: 0.
Epoch 8/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.4232 - acc: 0.8250
Epoch 9/100
8000/8000 [==============================] - 2s 286us/step - loss

In [17]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1556,   39],
       [ 279,  126]], dtype=int64)

# Improving the ANN performance
## Grid Search to improve accuracy with hyper parameter tuning

In [16]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.grid_search import GridSearchCV
#The sequential library is used to initialize our neural network
from keras.models import Sequential
#The dense library is used to build the layers of our ANN
from keras.layers import Dense


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [ ]:
'''Here you can see that batch_size and nb_epoch are part of the classifier hyper parameters, whereas the optimizer is an 
architecture parameter.  If we want to fine tune the architecture parameter as well like optimizer, loss etc. - then we would
have to mention them when defining the build_classifier class as a parameter within brackets like this: 
def build_classifier(optimizer, loss).  In our case below I have chosen only to fine tune the optimizer only for now'''
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
    classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
#Next Set of lines are specific to grid search specification
parameters = {'batch_size': [25, 32],
              'nb_epoch': [100, 500],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier, 
                           param_grid = parameters, 
                           scoring = 'accuracy',
                           cv = 10)
grid_search.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  if __name__ == '__main__':


Epoch 1/1
7200/7200 [==============================] - 5s 687us/step - loss: 0.5849 - acc: 0.7954
Epoch 1/1
7200/7200 [==============================] - 5s 672us/step - loss: 0.5585 - acc: 0.7956
Epoch 1/1
7200/7200 [==============================] - 5s 676us/step - loss: 0.5626 - acc: 0.7950
Epoch 1/1
7200/7200 [==============================] - 5s 688us/step - loss: 0.5588 - acc: 0.7964
Epoch 1/1
7200/7200 [==============================] - 6s 796us/step - loss: 0.5799 - acc: 0.7921
Epoch 1/1
7200/7200 [==============================] - 5s 708us/step - loss: 0.5582 - acc: 0.7940
Epoch 1/1
7200/7200 [==============================] - 6s 812us/step - loss: 0.5504 - acc: 0.7971
Epoch 1/1
7200/7200 [==============================] - 6s 869us/step - loss: 0.5654 - acc: 0.7950
Epoch 1/1
7200/7200 [==============================] - 5s 752us/step - loss: 0.5627 - acc: 0.7939
Epoch 1/1
7200/7200 [==============================] - 5s 743us/step - loss: 0.5779 - acc: 0.7951
Epoch 1/1
7200/7200 

In [14]:
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_
best_parameters

{'batch_size': 25, 'nb_epoch': 100, 'optimizer': 'adam'}

In [15]:
best_accuracy

0.796

In [ ]:
# Predicting the Test set results
y_pred = grid_search.predict(X_test)
y_pred = (y_pred > 0.5)
# Making the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
cm